apiVersion: serving.kserve.io/v1alpha1
kind: LLMInferenceService
metadata:
  name: llm-d
  annotations:
    security.opendatahub.io/enable-auth: "false"
    prometheus.io/path: /metrics
    prometheus.io/port: "8000"
spec:
  replicas: 1
  model:
    uri: hf://Qwen/Qwen3-0.6B
    name: Qwen/Qwen3-0.6B
  router:
    scheduler:
      template:
        containers:
        - name: main
    route: {}
    gateway: {}
  template:
    tolerations: null
    containers:
      - name: main
        resources:
          requests:
            cpu: "4"
            memory: 16Gi
            nvidia.com/gpu: "1"
          limits:
            cpu: "4"
            memory: 16Gi
            nvidia.com/gpu: "1"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
            scheme: HTTPS
          initialDelaySeconds: 900
          periodSeconds: 60
          timeoutSeconds: 60
          failureThreshold: 1000
        readinessProbe:
          failureThreshold: 10000
          httpGet:
            path: /health
            port: 8000
            scheme: HTTPS
          initialDelaySeconds: 60
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 30
